name: AskETSII CI

on:
  push:

jobs:
  docker_image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.20

      - name: Check version and install dependecies
        run: make install

      - name: Run tests
        run: make test
