name: AskETSIIT Image

on:
  push:
    paths:
    - 'go.mod'
    - 'Makefile'
    - 'Dockerfile'

jobs:
  build_publish:
    runs-on: apline-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push the image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/asketsiit:latest